### ISSUE TITLE
trouble parsing vcf file

### ISSUE THREAD

**Issue by gregcaporaso** [W-L/ProblematicSites_SARS-CoV2#4]
I was in touch on Virological and mentioned that I was interested in using this mask. I'm trying to parse the VCF file, and it doesn't seem to be properly formatted (based on error messages from PyVCF). Here's an example of the issue that I'm running into:

First, I installed PyVCF:
```bash
$ conda install -c bioconda -c conda-forge pyvcf
```

Then, download the vcf file from your repo:
```bash
$ wget https://raw.githubusercontent.com/W-L/ProblematicSites_SARS-CoV2/master/problematic_sites_sarsCov2.vcf
```

Then, in an IPython interpreter, try to load the VCF file:
```python
In [1]: import vcf

In [2]: vcf_reader = vcf.Reader(open('/Users/gregcaporaso/temp/problematic_sites_sarsCov2.vcf'))
Traceback (most recent call last):

  File "/Users/gregcaporaso/opt/miniconda3/envs/genome-sampler/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-3-c3038c78246c>", line 1, in <module>
    vcf_reader = vcf.Reader(open('/Users/gregcaporaso/temp/problematic_sites_sarsCov2.vcf'))

  File "/Users/gregcaporaso/opt/miniconda3/envs/genome-sampler/lib/python3.6/site-packages/vcf/parser.py", line 300, in __init__
    self._parse_metainfo()

  File "/Users/gregcaporaso/opt/miniconda3/envs/genome-sampler/lib/python3.6/site-packages/vcf/parser.py", line 326, in _parse_metainfo
    key, val = parser.read_filter(line)

  File "/Users/gregcaporaso/opt/miniconda3/envs/genome-sampler/lib/python3.6/site-packages/vcf/parser.py", line 143, in read_filter
    "One of the FILTER lines is malformed: %s" % filter_string)

  File "<string>", line unknown
SyntaxError: One of the FILTER lines is malformed: ##FILTER=<Description="Masking recommendation"
```

The issue seems to be that it's missing an `ID` field and a closing bracket (`>`). I can get past this error by modifying line 6 in the VCF file to look like the following:

```
##FILTER=<ID=SC2Mask,Description="Masking recommendation">
```

but I then get the following error:

```python
In [11]: vcf_reader = vcf.Reader(open('/Users/gregcaporaso/temp/problematic_sites_sarsCov2.vcf'))
Traceback (most recent call last):

  File "/Users/gregcaporaso/opt/miniconda3/envs/genome-sampler/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-11-c3038c78246c>", line 1, in <module>
    vcf_reader = vcf.Reader(open('/Users/gregcaporaso/temp/problematic_sites_sarsCov2.vcf'))

  File "/Users/gregcaporaso/opt/miniconda3/envs/genome-sampler/lib/python3.6/site-packages/vcf/parser.py", line 300, in __init__
    self._parse_metainfo()

  File "/Users/gregcaporaso/opt/miniconda3/envs/genome-sampler/lib/python3.6/site-packages/vcf/parser.py", line 322, in _parse_metainfo
    key, val = parser.read_info(line)

  File "/Users/gregcaporaso/opt/miniconda3/envs/genome-sampler/lib/python3.6/site-packages/vcf/parser.py", line 128, in read_info
    "One of the INFO lines is malformed: %s" % info_string)

  File "<string>", line unknown
SyntaxError: One of the INFO lines is malformed: ##INFO=<Description="Initials of submitter"
```

I'm not very familiar with VCF files, but PyVCF seems to be well-established and well-tested (the error messages are very informative so far, which is a plus). 

Should this file be parsable with PyVCF? If so, I think it would make sense to set up continuous integration testing (e.g., with TravisCI) and add a test that tries to parse the VCF file with PyVCF each time it's updated. That would let you get alerted if the file isn't formatted correctly.

**Comment by conorwalker** [comment]
Hi Greg, thanks for your suggestions. We have now reformatted the VCF and it should be in compliance with VCF v4.3 specification. Specifically, the metadata for each site is now all encoded as key=value pairs in the INFO column, rather than using multiple columns.

I've also set up tests (using Travis CI) to check for error/warning-free parsing when using either BCFtools or PyVCF.

Let me know if any issues persist.

**Comment by gregcaporaso** [comment]
Looks like it's working now - thank you!

**Comment by gregcaporaso** [comment]
Actually, I think I spoke too soon, I seem to still be having issues parsing that file:

```
$ wget https://raw.githubusercontent.com/W-L/ProblematicSites_SARS-CoV2/master/problematic_sites_sarsCov2.vcf
$ ipython
Python 3.6.10 | packaged by conda-forge | (default, Apr 24 2020, 16:27:41)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.16.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import vcf

In [3]: vcf_reader = vcf.Reader(open('problematic_sites_sarsCov2.vcf'))

In [4]: for record in vcf_reader:
   ...:     print(record)
   ...:
Record(CHROM=MN908947.3, POS=1, REF=A, ALT=[None])
Record(CHROM=MN908947.3, POS=2, REF=T, ALT=[None])
Record(CHROM=MN908947.3, POS=3, REF=T, ALT=[None])
Record(CHROM=MN908947.3, POS=4, REF=A, ALT=[None])
Record(CHROM=MN908947.3, POS=5, REF=A, ALT=[None])
Record(CHROM=MN908947.3, POS=6, REF=A, ALT=[None])
Record(CHROM=MN908947.3, POS=7, REF=G, ALT=[None])
Record(CHROM=MN908947.3, POS=8, REF=G, ALT=[None])
Record(CHROM=MN908947.3, POS=9, REF=T, ALT=[None])
Record(CHROM=MN908947.3, POS=10, REF=T, ALT=[None])
Record(CHROM=MN908947.3, POS=11, REF=T, ALT=[None])
Record(CHROM=MN908947.3, POS=12, REF=A, ALT=[None])
Record(CHROM=MN908947.3, POS=13, REF=T, ALT=[None])
Record(CHROM=MN908947.3, POS=14, REF=A, ALT=[None])
Record(CHROM=MN908947.3, POS=15, REF=C, ALT=[None])
Record(CHROM=MN908947.3, POS=16, REF=C, ALT=[None])
Record(CHROM=MN908947.3, POS=17, REF=T, ALT=[None])
Record(CHROM=MN908947.3, POS=18, REF=T, ALT=[None])
Record(CHROM=MN908947.3, POS=19, REF=C, ALT=[None])
Record(CHROM=MN908947.3, POS=20, REF=C, ALT=[None])
Record(CHROM=MN908947.3, POS=21, REF=C, ALT=[None])
Record(CHROM=MN908947.3, POS=22, REF=A, ALT=[None])
Record(CHROM=MN908947.3, POS=23, REF=G, ALT=[None])
Record(CHROM=MN908947.3, POS=24, REF=G, ALT=[None])
Record(CHROM=MN908947.3, POS=25, REF=T, ALT=[None])
Record(CHROM=MN908947.3, POS=26, REF=A, ALT=[None])
Record(CHROM=MN908947.3, POS=27, REF=A, ALT=[None])
Record(CHROM=MN908947.3, POS=28, REF=C, ALT=[None])
Record(CHROM=MN908947.3, POS=29, REF=A, ALT=[None])
Record(CHROM=MN908947.3, POS=30, REF=A, ALT=[None])
Record(CHROM=MN908947.3, POS=31, REF=A, ALT=[None])
Record(CHROM=MN908947.3, POS=32, REF=C, ALT=[None])
Record(CHROM=MN908947.3, POS=33, REF=C, ALT=[None])
Record(CHROM=MN908947.3, POS=34, REF=A, ALT=[None])
Record(CHROM=MN908947.3, POS=35, REF=A, ALT=[None])
Record(CHROM=MN908947.3, POS=36, REF=C, ALT=[None])
Record(CHROM=MN908947.3, POS=37, REF=C, ALT=[None])
Record(CHROM=MN908947.3, POS=38, REF=A, ALT=[None])
Record(CHROM=MN908947.3, POS=39, REF=A, ALT=[None])
Record(CHROM=MN908947.3, POS=40, REF=C, ALT=[None])
Record(CHROM=MN908947.3, POS=41, REF=T, ALT=[None])
Record(CHROM=MN908947.3, POS=42, REF=T, ALT=[None])
Record(CHROM=MN908947.3, POS=43, REF=T, ALT=[None])
Record(CHROM=MN908947.3, POS=44, REF=C, ALT=[None])
Record(CHROM=MN908947.3, POS=45, REF=G, ALT=[None])
Record(CHROM=MN908947.3, POS=46, REF=A, ALT=[None])
Record(CHROM=MN908947.3, POS=47, REF=T, ALT=[None])
Record(CHROM=MN908947.3, POS=48, REF=C, ALT=[None])
Record(CHROM=MN908947.3, POS=49, REF=T, ALT=[None])
Record(CHROM=MN908947.3, POS=50, REF=C, ALT=[None])
Record(CHROM=MN908947.3, POS=51, REF=T, ALT=[None])
Record(CHROM=MN908947.3, POS=52, REF=T, ALT=[None])
Record(CHROM=MN908947.3, POS=53, REF=G, ALT=[None])
Record(CHROM=MN908947.3, POS=54, REF=T, ALT=[None])
Record(CHROM=MN908947.3, POS=55, REF=A, ALT=[None])
Record(CHROM=MN908947.3, POS=76, REF=T, ALT=[W, A, C])
Record(CHROM=MN908947.3, POS=78, REF=T, ALT=[Y, K, W, A, G, C])
Record(CHROM=MN908947.3, POS=150, REF=T, ALT=[C, Y])
Record(CHROM=MN908947.3, POS=153, REF=T, ALT=[G, Y])
Record(CHROM=MN908947.3, POS=538, REF=A, ALT=[W])
Record(CHROM=MN908947.3, POS=635, REF=C, ALT=[Y, T])
Record(CHROM=MN908947.3, POS=660, REF=G, ALT=[K])
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-cedbcb885634> in <module>
----> 1 for record in vcf_reader:
      2     print(record)
      3

~/opt/miniconda3/envs/genome-sampler/lib/python3.6/site-packages/vcf/parser.py in __next__(self)
    584
    585         if fmt is not None:
--> 586             samples = self._parse_samples(row[9:], fmt, record)
    587             record.samples = samples
    588

~/opt/miniconda3/envs/genome-sampler/lib/python3.6/site-packages/vcf/parser.py in _parse_samples(self, samples, samp_fmt, site)
    444         # check whether we already know how to parse this format
    445         if samp_fmt not in self._format_cache:
--> 446             self._format_cache[samp_fmt] = self._parse_sample_format(samp_fmt)
    447         samp_fmt = self._format_cache[samp_fmt]
    448

~/opt/miniconda3/envs/genome-sampler/lib/python3.6/site-packages/vcf/parser.py in _parse_sample_format(self, samp_fmt)
    418     def _parse_sample_format(self, samp_fmt):
    419         """ Parse the format of the calls in this _Record """
--> 420         samp_fmt = make_calldata_tuple(samp_fmt.split(':'))
    421
    422         for fmt in samp_fmt._fields:

~/opt/miniconda3/envs/genome-sampler/lib/python3.6/site-packages/vcf/model.py in make_calldata_tuple(fields)
    662     """ Return a namedtuple for a given call format """
    663
--> 664     class CallData(collections.namedtuple('calldata', fields)):
    665         __slots__ = ()
    666

~/opt/miniconda3/envs/genome-sampler/lib/python3.6/collections/__init__.py in namedtuple(typename, field_names, verbose, rename, module)
    399         if not name.isidentifier():
    400             raise ValueError('Type names and field names must be valid '
--> 401                              'identifiers: %r' % name)
    402         if _iskeyword(name):
    403             raise ValueError('Type names and field names cannot be a '

ValueError: Type names and field names must be valid identifiers: 'Virology;GENE=gene-orf1ab;AA_POS=165;AA_REF=H;AA_ALT=L'
```

**Comment by conorwalker** [comment]
Fixed, there was a space in one of the SRC_LAB values added on Friday, this is caught in the test now and the file should parse fine.

**Comment by gregcaporaso** [comment]
That seems to be working for me now, thank you again for the help!
